/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum reloc_type_x86_64 {
    X86_64_RELOC_UNSIGNED = 0,
    X86_64_RELOC_SIGNED = 1,
    X86_64_RELOC_BRANCH = 2,
    X86_64_RELOC_GOT_LOAD = 3,
    X86_64_RELOC_GOT = 4,
    X86_64_RELOC_SUBTRACTOR = 5,
    X86_64_RELOC_SIGNED_1 = 6,
    X86_64_RELOC_SIGNED_2 = 7,
    X86_64_RELOC_SIGNED_4 = 8,
    X86_64_RELOC_TLV = 9,
}
