/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum reloc_type_arm64 {
    ARM64_RELOC_UNSIGNED = 0,
    ARM64_RELOC_SUBTRACTOR = 1,
    ARM64_RELOC_BRANCH26 = 2,
    ARM64_RELOC_PAGE21 = 3,
    ARM64_RELOC_PAGEOFF12 = 4,
    ARM64_RELOC_GOT_LOAD_PAGE21 = 5,
    ARM64_RELOC_GOT_LOAD_PAGEOFF12 = 6,
    ARM64_RELOC_POINTER_TO_GOT = 7,
    ARM64_RELOC_TLVP_LOAD_PAGE21 = 8,
    ARM64_RELOC_TLVP_LOAD_PAGEOFF12 = 9,
    ARM64_RELOC_ADDEND = 10,
}
